/* ============================================================
   HENGSHENG MARBLE — 全站統一產品參數數據源 (Single Source of Truth)
   ------------------------------------------------------------
   用途：產品詳情頁參數表、列表卡片參數摘要、對比頁統一維度對齊表
   結構：
     FIELDS      欄位定義（key / 分組 / 中英名稱 / 單位）
     CAT_DEFAULTS 品類預設值（同品類共用欄位）
     PRODUCTS    逐款差異值（覆蓋品類預設）
   取值：字串以「|」分隔中英；無「|」表示中英相同
   缺失：欄位未提供 → 前端顯示「不支援／無 / Not applicable」
   維護：新增產品只需在 PRODUCTS 增加一筆（key = "品類/slug"）
   [CRITICAL CODE - DO NOT DELETE OR MODIFY]
   ============================================================ */
(function () {
  'use strict';
  if (window.__HSST_SPECS_LOADED__) return;
  window.__HSST_SPECS_LOADED__ = true;

  var GROUPS = [
    { key: "basic", name: "基本資料|Basic Information" },
    { key: "dim", name: "尺寸規格|Dimensions & Sizing" },
    { key: "phys", name: "物理性能|Physical Performance" },
    { key: "fab", name: "加工與安裝|Fabrication & Installation" },
    { key: "cert", name: "認證與保養|Certification & Care" },
    { key: "comm", name: "商務條款|Commercial Terms" },
  ];

  var FIELDS = [
    { key: "type", group: "basic", name: "石材類型|Stone Type", unit: null, meta: null },
    { key: "origin", group: "basic", name: "產地|Origin", unit: null, meta: null },
    { key: "colour", group: "basic", name: "色系|Colour Family", unit: null, meta: null },
    { key: "grade", group: "basic", name: "板材等級|Slab Grade", unit: null, meta: "外觀檢驗|Visual inspection" },
    { key: "slab", group: "dim", name: "常規板材規格|Standard Slab Size", unit: null, meta: "出廠鋸切規格|Mill cutting spec" },
    { key: "size", group: "dim", name: "製品常規尺寸|Standard Product Size", unit: null, meta: null },
    { key: "thickness", group: "dim", name: "常規厚度|Available Thickness", unit: null, meta: "卡尺實測|Caliper measurement" },
    { key: "tolerance", group: "dim", name: "尺寸公差|Dimensional Tolerance", unit: null, meta: "BS EN 12058|BS EN 12058" },
    { key: "density", group: "phys", name: "密度|Density", unit: "g/cm³", meta: "ASTM C97 / EN 1936|ASTM C97 / EN 1936" },
    { key: "absorption", group: "phys", name: "吸水率|Water Absorption", unit: "%", meta: "ASTM C97|ASTM C97" },
    { key: "compressive", group: "phys", name: "抗壓強度|Compressive Strength", unit: "MPa", meta: "ASTM C170 / EN 1926|ASTM C170 / EN 1926" },
    { key: "flexural", group: "phys", name: "抗彎強度|Flexural Strength", unit: "MPa", meta: "ASTM C880 / EN 12372|ASTM C880 / EN 12372" },
    { key: "mohs", group: "phys", name: "莫氏硬度|Mohs Hardness", unit: null, meta: "EN 14157|EN 14157" },
    { key: "abrasion", group: "phys", name: "耐磨性|Abrasion Resistance", unit: null, meta: "EN 14157|EN 14157" },
    { key: "gloss", group: "phys", name: "光澤度|Gloss Level", unit: "GU", meta: "ISO 2813（60°）|ISO 2813 (60°)" },
    { key: "slip", group: "phys", name: "防滑等級|Slip Resistance", unit: null, meta: "BS EN 14231|BS EN 14231" },
    { key: "freeze", group: "phys", name: "耐凍融|Frost Resistance", unit: null, meta: "BS EN 12371|BS EN 12371" },
    { key: "heat", group: "phys", name: "耐熱溫度|Heat Resistance", unit: "°C", meta: "EN 438-2|EN 438-2" },
    { key: "stain", group: "phys", name: "耐污等級|Stain Resistance", unit: null, meta: "EN 438-2|EN 438-2" },
    { key: "acid", group: "phys", name: "耐酸性|Acid Resistance", unit: null, meta: "EN 13529|EN 13529" },
    { key: "radio", group: "phys", name: "放射性等級|Radioactivity Class", unit: null, meta: "GB 6566|GB 6566" },
    { key: "light", group: "phys", name: "透光率|Light Transmission", unit: "%", meta: "光通量法|Luminous flux method" },
    { key: "edge", group: "fab", name: "邊型加工|Edge Profile", unit: null, meta: null },
    { key: "install", group: "fab", name: "安裝方式|Installation Method", unit: null, meta: null },
    { key: "seam", group: "fab", name: "接縫處理|Joint Treatment", unit: null, meta: null },
    { key: "substrate", group: "fab", name: "適用基材|Compatible Substrate", unit: null, meta: null },
    { key: "load", group: "fab", name: "承重／承載等級|Load Rating", unit: null, meta: "結構荷載計算|Structural load calculation" },
    { key: "precision", group: "fab", name: "加工精度|Machining Precision", unit: null, meta: "廠內 QC 量測|In-house QC measurement" },
    { key: "minfeature", group: "fab", name: "最小加工尺寸|Minimum Feature Size", unit: null, meta: null },
    { key: "cert", group: "cert", name: "認證標準|Certification", unit: null, meta: "第三方認證|Third-party certification" },
    { key: "standard", group: "cert", name: "執行標準|Applicable Standard", unit: null, meta: "產品執行標準|Product standard" },
    { key: "maintain", group: "cert", name: "保養週期|Maintenance Cycle", unit: null, meta: null },
    { key: "warranty", group: "cert", name: "品質保固|Warranty", unit: null, meta: null },
    { key: "price", group: "comm", name: "價格單位|Price Unit", unit: null, meta: null },
    { key: "moq", group: "comm", name: "最小訂購量|Minimum Order Quantity", unit: null, meta: null },
    { key: "lead", group: "comm", name: "供貨週期|Lead Time", unit: null, meta: null },
    { key: "pack", group: "comm", name: "包裝方式|Packaging", unit: null, meta: null },
  ];

  var CAT_DEFAULTS = {
    "beige-marble": {
      "grade": "A 級（無裂、無補膠）|Grade A (no cracks, no resin fill)",
      "slab": "3200×1600mm / 3050×1440mm",
      "thickness": "18 / 20 / 30mm（常備）；可訂 15–50mm|18 / 20 / 30 mm (stock); 15–50 mm to order",
      "tolerance": "±1.0mm（磨光面）|±1.0 mm (polished face)",
      "radio": "A 類 Class A（GB 6566）|Class A (GB 6566)",
      "edge": "直邊／圓邊／斜邊／羅馬邊|Straight / Bevel / Bullnose / Ogee",
      "install": "濕貼水泥砂漿／不鏽鋼乾掛|Wet-set mortar / Stainless steel dry-hang",
      "seam": "雲石膠無縫拼接（同紋對接）|Seamless epoxy jointing (pattern-matched)",
      "cert": "ISO 9001 · ASTM C97／C170 · GB 6566 A 類|ISO 9001 · ASTM C97/C170 · GB 6566 Class A",
      "maintain": "每 12 個月晶面保養一次|Crystallisation maintenance every 12 months",
      "warranty": "出廠品質保固 10 年（不含人為損壞）|10-year factory warranty (excl. accidental damage)",
      "price": "HK$／平方呎（按板面實碼計）|HK$ per sq. ft. (measured slab area)",
      "moq": "30 m²（可混色）|30 m² (mixed colours accepted)",
      "lead": "現貨 7–10 個工作天；訂造 20–30 天|Stock 7–10 working days; custom 20–30 days",
      "pack": "木箱 A 字架，每箱 8–10 片|Wooden A-frame crate, 8–10 slabs per crate",
    },
    "black-marble": {
      "grade": "A 級（無裂、無補膠）|Grade A (no cracks, no resin fill)",
      "slab": "3200×1600mm / 3050×1440mm",
      "thickness": "18 / 20 / 30mm（常備）；可訂 15–50mm|18 / 20 / 30 mm (stock); 15–50 mm to order",
      "tolerance": "±1.0mm（磨光面）|±1.0 mm (polished face)",
      "radio": "A 類 Class A（GB 6566）|Class A (GB 6566)",
      "edge": "直邊／圓邊／斜邊／羅馬邊|Straight / Bevel / Bullnose / Ogee",
      "install": "濕貼水泥砂漿／不鏽鋼乾掛|Wet-set mortar / Stainless steel dry-hang",
      "seam": "雲石膠無縫拼接（同紋對接）|Seamless epoxy jointing (pattern-matched)",
      "cert": "ISO 9001 · ASTM C97／C170 · GB 6566 A 類|ISO 9001 · ASTM C97/C170 · GB 6566 Class A",
      "maintain": "每 12 個月晶面保養一次|Crystallisation maintenance every 12 months",
      "warranty": "出廠品質保固 10 年（不含人為損壞）|10-year factory warranty (excl. accidental damage)",
      "price": "HK$／平方呎（按板面實碼計）|HK$ per sq. ft. (measured slab area)",
      "moq": "30 m²（可混色）|30 m² (mixed colours accepted)",
      "lead": "現貨 7–10 個工作天；訂造 20–30 天|Stock 7–10 working days; custom 20–30 days",
      "pack": "木箱 A 字架，每箱 8–10 片|Wooden A-frame crate, 8–10 slabs per crate",
    },
    "custom-craft": {
      "type": "石材加工工藝|Stone Fabrication Process",
      "origin": "香港／內地自有加工廠|In-house workshop: Hong Kong / Mainland",
      "colour": "不適用（工藝服務）|Not applicable (service)",
      "substrate": "適用雲石／麻石／石英石／人造石|Suitable for marble / granite / quartz / engineered stone",
      "install": "廠內加工＋現場收口|In-house fabrication with on-site finishing",
      "cert": "ISO 9001 · 每批附工藝品質檢驗報告|ISO 9001 · Process QC report per batch",
      "maintain": "按成品石材保養指引|Follow care guide of finished stone",
      "warranty": "工藝保固 5 年|5-year workmanship warranty",
      "price": "HK$／項（按圖紙與數量報價）|HK$ per item (quoted by drawing & quantity)",
      "moq": "1 項（最低消費 HK$2,000）|1 item (minimum order HK$2,000)",
      "lead": "15–30 個工作天|15–30 working days",
      "pack": "木箱固定，防撞保護|Crated with impact protection",
    },
    "engineered-stone": {
      "grade": "優等品（無氣孔、無色差）|Premium grade (non-porous, no shade variation)",
      "slab": "3200×1600mm / 3050×1440mm",
      "tolerance": "±0.5mm（定厚磨光）|±0.5 mm (calibrated & polished)",
      "radio": "A 類 Class A（GB 6566）|Class A (GB 6566)",
      "acid": "耐日常弱酸鹼；忌強酸|Resists mild acids/alkalis; avoid strong acid",
      "edge": "直邊／圓邊／斜邊／羅馬邊|Straight / Bevel / Bullnose / Ogee",
      "install": "專用黏合劑＋墊條支撐|Adhesive bedding with support batten",
      "seam": "同色專用膠無縫拼接|Seamless jointing with colour-matched adhesive",
      "substrate": "木板基層／水泥砂漿／舊檯面覆蓋|Plywood substrate / sand-cement / overlay on existing top",
      "cert": "ISO 9001 · NSF/ANSI 51 · GB 6566 A 類|ISO 9001 · NSF/ANSI 51 · GB 6566 Class A",
      "maintain": "中性清潔劑日常擦拭；每 6 個月封護一次|Neutral detergent daily; seal every 6 months",
      "warranty": "10 年有限保固（非結構性）|10-year limited warranty (non-structural)",
      "price": "HK$／平方呎（按檯面實碼計）|HK$ per sq. ft. (measured top area)",
      "moq": "20 m²|20 m²",
      "lead": "常規色 10–14 天；訂色 25–35 天|Stock colours 10–14 days; custom colours 25–35 days",
      "pack": "木托盤＋護角，每托 12–15 片|Pallet with corner guards, 12–15 slabs per pallet",
    },
    "engineering-stone-varieties": {
      "type": "天然花崗巖（麻石）|Natural Granite",
      "origin": "中國福建／山東礦區（可選印度）|Fujian / Shandong quarries, China (India optional)",
      "freeze": "50 次凍融循環合格（BS EN 12371）|50 freeze-thaw cycles pass (BS EN 12371)",
      "lead": "15–25 個工作天（訂造 30–40 天）|15–25 working days (custom 30–40 days)",
      "pack": "木托盤纏繞膜，每托 40–60 件|Pallet with stretch film, 40–60 pieces per pallet",
      "radio": "A 類 Class A（GB 6566）|Class A (GB 6566)",
      "tolerance": "±2.0mm（機切面）|±2.0 mm (sawn face)",
      "install": "水泥砂漿濕鋪／膨脹螺栓固定|Wet-set sand-cement / expansion bolt anchoring",
      "seam": "5–8mm 水泥砂漿勾縫|5–8 mm sand-cement pointing",
      "cert": "ISO 9001 · BS EN 1341／1342／1343 · GB 6566 A 類|ISO 9001 · BS EN 1341/1342/1343 · GB 6566 Class A",
      "maintain": "高壓水洗；每 24 個月檢查勾縫|Pressure wash; repoint inspection every 24 months",
      "warranty": "戶外耐候保固 15 年|15-year outdoor weathering warranty",
    },
    "granite-collection": {
      "grade": "A 級（無裂、無補膠）|Grade A (no cracks, no resin fill)",
      "slab": "3200×1600mm / 3050×1440mm",
      "thickness": "18 / 20 / 30mm（常備）；可訂 15–50mm|18 / 20 / 30 mm (stock); 15–50 mm to order",
      "tolerance": "±1.0mm（磨光面）|±1.0 mm (polished face)",
      "radio": "A 類 Class A（GB 6566）|Class A (GB 6566)",
      "edge": "直邊／圓邊／斜邊／羅馬邊|Straight / Bevel / Bullnose / Ogee",
      "install": "濕貼水泥砂漿／不鏽鋼乾掛|Wet-set mortar / Stainless steel dry-hang",
      "seam": "雲石膠無縫拼接（同紋對接）|Seamless epoxy jointing (pattern-matched)",
      "cert": "ISO 9001 · ASTM C97／C170 · GB 6566 A 類|ISO 9001 · ASTM C97/C170 · GB 6566 Class A",
      "maintain": "每 12 個月晶面保養一次|Crystallisation maintenance every 12 months",
      "warranty": "出廠品質保固 10 年（不含人為損壞）|10-year factory warranty (excl. accidental damage)",
      "price": "HK$／平方呎（按板面實碼計）|HK$ per sq. ft. (measured slab area)",
      "moq": "30 m²（可混色）|30 m² (mixed colours accepted)",
      "lead": "現貨 7–10 個工作天；訂造 20–30 天|Stock 7–10 working days; custom 20–30 days",
      "pack": "木箱 A 字架，每箱 8–10 片|Wooden A-frame crate, 8–10 slabs per crate",
    },
    "grey-marble": {
      "grade": "A 級（無裂、無補膠）|Grade A (no cracks, no resin fill)",
      "slab": "3200×1600mm / 3050×1440mm",
      "thickness": "18 / 20 / 30mm（常備）；可訂 15–50mm|18 / 20 / 30 mm (stock); 15–50 mm to order",
      "tolerance": "±1.0mm（磨光面）|±1.0 mm (polished face)",
      "radio": "A 類 Class A（GB 6566）|Class A (GB 6566)",
      "edge": "直邊／圓邊／斜邊／羅馬邊|Straight / Bevel / Bullnose / Ogee",
      "install": "濕貼水泥砂漿／不鏽鋼乾掛|Wet-set mortar / Stainless steel dry-hang",
      "seam": "雲石膠無縫拼接（同紋對接）|Seamless epoxy jointing (pattern-matched)",
      "cert": "ISO 9001 · ASTM C97／C170 · GB 6566 A 類|ISO 9001 · ASTM C97/C170 · GB 6566 Class A",
      "maintain": "每 12 個月晶面保養一次|Crystallisation maintenance every 12 months",
      "warranty": "出廠品質保固 10 年（不含人為損壞）|10-year factory warranty (excl. accidental damage)",
      "price": "HK$／平方呎（按板面實碼計）|HK$ per sq. ft. (measured slab area)",
      "moq": "30 m²（可混色）|30 m² (mixed colours accepted)",
      "lead": "現貨 7–10 個工作天；訂造 20–30 天|Stock 7–10 working days; custom 20–30 days",
      "pack": "木箱 A 字架，每箱 8–10 片|Wooden A-frame crate, 8–10 slabs per crate",
    },
    "luxury-stone": {
      "grade": "A 級（無裂、無補膠）|Grade A (no cracks, no resin fill)",
      "slab": "3200×1600mm / 3050×1440mm",
      "thickness": "18 / 20 / 30mm（常備）；可訂 15–50mm|18 / 20 / 30 mm (stock); 15–50 mm to order",
      "tolerance": "±1.0mm（磨光面）|±1.0 mm (polished face)",
      "radio": "A 類 Class A（GB 6566）|Class A (GB 6566)",
      "edge": "直邊／圓邊／斜邊／羅馬邊|Straight / Bevel / Bullnose / Ogee",
      "install": "濕貼水泥砂漿／不鏽鋼乾掛|Wet-set mortar / Stainless steel dry-hang",
      "seam": "雲石膠無縫拼接（同紋對接）|Seamless epoxy jointing (pattern-matched)",
      "cert": "ISO 9001 · ASTM C97／C170 · GB 6566 A 類|ISO 9001 · ASTM C97/C170 · GB 6566 Class A",
      "maintain": "每 12 個月晶面保養一次|Crystallisation maintenance every 12 months",
      "warranty": "出廠品質保固 10 年（不含人為損壞）|10-year factory warranty (excl. accidental damage)",
      "price": "HK$／平方呎（按板面實碼計）|HK$ per sq. ft. (measured slab area)",
      "moq": "30 m²（可混色）|30 m² (mixed colours accepted)",
      "lead": "現貨 7–10 個工作天；訂造 20–30 天|Stock 7–10 working days; custom 20–30 days",
      "pack": "木箱 A 字架，每箱 8–10 片|Wooden A-frame crate, 8–10 slabs per crate",
    },
    "marble-furniture": {
      "type": "雲石家俬（天然石材＋金屬／木框腳）|Marble Furniture (natural stone + metal/timber frame)",
      "origin": "意大利／土耳其／中國石材，香港組裝|Italian / Turkish / Chinese stone, assembled in Hong Kong",
      "colour": "按選材而定（白／米／灰／黑）|Depends on stone selection (white / beige / grey / black)",
      "thickness": "檯面 20 / 30 / 40 / 50mm|Top 20 / 30 / 40 / 50 mm",
      "tolerance": "±1.0mm（檯面成品）|±1.0 mm (finished top)",
      "density": "2.68 – 2.74",
      "absorption": "0.10 – 0.28",
      "compressive": "110 – 155",
      "flexural": "10 – 19",
      "mohs": "3.0 – 4.0",
      "abrasion": "≤ 25 mm（BS EN 14157）|≤ 25 mm (BS EN 14157)",
      "gloss": "80 – 90（鏡面拋光）|80–90 (mirror polish)",
      "heat": "≤ 120（建議加隔熱墊）|≤ 120 (heat pad recommended)",
      "stain": "封護後達 5 級（EN 438）|Class 5 after sealing (EN 438)",
      "acid": "雲石不耐酸；石英石耐日常酸鹼|Marble acid-sensitive; quartz resists mild acids",
      "radio": "A 類 Class A（GB 6566）|Class A (GB 6566)",
      "edge": "圓邊／斜邊／羅馬邊／法國邊|Bullnose / Bevel / Ogee / French edge",
      "install": "到場組裝（含調平與收口）|On-site assembly incl. levelling and joint finishing",
      "seam": "整料無拼接（>2400mm 採無縫拼接）|Single slab; seamless joint above 2400 mm",
      "substrate": "雲石／麻石／石英石檯面＋金屬或實木框腳|Marble / granite / quartz top with metal or timber frame",
      "cert": "ISO 9001 · 甲醛釋放 E1 級|ISO 9001 · Formaldehyde emission Class E1",
      "maintain": "每 6 個月雲石封護；忌酸性清潔劑|Seal every 6 months; avoid acidic cleaners",
      "warranty": "結構保固 5 年；石材檯面 10 年|5-year frame warranty; 10-year stone top warranty",
      "price": "HK$／件（按尺寸與選材報價）|HK$ per piece (quoted by size & stone selection)",
      "moq": "1 件（訂造）|1 piece (made to order)",
      "lead": "25–40 個工作天|25–40 working days",
      "pack": "木箱＋珍珠棉，分件包裝|Wooden crate with pearl-cotton, knock-down packing",
    },
    "new-arrivals": {
      "grade": "A 級（無裂、無補膠）|Grade A (no cracks, no resin fill)",
      "slab": "3200×1600mm / 3050×1440mm",
      "thickness": "18 / 20 / 30mm（常備）；可訂 15–50mm|18 / 20 / 30 mm (stock); 15–50 mm to order",
      "tolerance": "±1.0mm（磨光面）|±1.0 mm (polished face)",
      "radio": "A 類 Class A（GB 6566）|Class A (GB 6566)",
      "edge": "直邊／圓邊／斜邊／羅馬邊|Straight / Bevel / Bullnose / Ogee",
      "install": "濕貼水泥砂漿／不鏽鋼乾掛|Wet-set mortar / Stainless steel dry-hang",
      "seam": "雲石膠無縫拼接（同紋對接）|Seamless epoxy jointing (pattern-matched)",
      "cert": "ISO 9001 · ASTM C97／C170 · GB 6566 A 類|ISO 9001 · ASTM C97/C170 · GB 6566 Class A",
      "maintain": "每 12 個月晶面保養一次|Crystallisation maintenance every 12 months",
      "warranty": "出廠品質保固 10 年（不含人為損壞）|10-year factory warranty (excl. accidental damage)",
      "price": "HK$／平方呎（按板面實碼計）|HK$ per sq. ft. (measured slab area)",
      "moq": "30 m²（可混色）|30 m² (mixed colours accepted)",
      "lead": "現貨 7–10 個工作天；訂造 20–30 天|Stock 7–10 working days; custom 20–30 days",
      "pack": "木箱 A 字架，每箱 8–10 片|Wooden A-frame crate, 8–10 slabs per crate",
    },
    "project-stone": {
      "grade": "A 級（無裂、無補膠）|Grade A (no cracks, no resin fill)",
      "slab": "3200×1600mm / 3050×1440mm",
      "thickness": "18 / 20 / 30mm（常備）；可訂 15–50mm|18 / 20 / 30 mm (stock); 15–50 mm to order",
      "tolerance": "±1.0mm（磨光面）|±1.0 mm (polished face)",
      "radio": "A 類 Class A（GB 6566）|Class A (GB 6566)",
      "edge": "直邊／圓邊／斜邊／羅馬邊|Straight / Bevel / Bullnose / Ogee",
      "install": "濕貼水泥砂漿／不鏽鋼乾掛|Wet-set mortar / Stainless steel dry-hang",
      "seam": "雲石膠無縫拼接（同紋對接）|Seamless epoxy jointing (pattern-matched)",
      "cert": "ISO 9001 · ASTM C97／C170 · GB 6566 A 類|ISO 9001 · ASTM C97/C170 · GB 6566 Class A",
      "maintain": "每 12 個月晶面保養一次|Crystallisation maintenance every 12 months",
      "warranty": "出廠品質保固 10 年（不含人為損壞）|10-year factory warranty (excl. accidental damage)",
      "price": "HK$／平方呎（按板面實碼計）|HK$ per sq. ft. (measured slab area)",
      "moq": "30 m²（可混色）|30 m² (mixed colours accepted)",
      "lead": "現貨 7–10 個工作天；訂造 20–30 天|Stock 7–10 working days; custom 20–30 days",
      "pack": "木箱 A 字架，每箱 8–10 片|Wooden A-frame crate, 8–10 slabs per crate",
    },
    "travertine-sandstone": {
      "grade": "A 級（無裂、無補膠）|Grade A (no cracks, no resin fill)",
      "slab": "3200×1600mm / 3050×1440mm",
      "thickness": "18 / 20 / 30mm（常備）；可訂 15–50mm|18 / 20 / 30 mm (stock); 15–50 mm to order",
      "tolerance": "±1.0mm（磨光面）|±1.0 mm (polished face)",
      "radio": "A 類 Class A（GB 6566）|Class A (GB 6566)",
      "edge": "直邊／圓邊／斜邊／羅馬邊|Straight / Bevel / Bullnose / Ogee",
      "install": "濕貼水泥砂漿／不鏽鋼乾掛|Wet-set mortar / Stainless steel dry-hang",
      "seam": "雲石膠無縫拼接（同紋對接）|Seamless epoxy jointing (pattern-matched)",
      "cert": "ISO 9001 · ASTM C97／C170 · GB 6566 A 類|ISO 9001 · ASTM C97/C170 · GB 6566 Class A",
      "maintain": "每 12 個月晶面保養一次|Crystallisation maintenance every 12 months",
      "warranty": "出廠品質保固 10 年（不含人為損壞）|10-year factory warranty (excl. accidental damage)",
      "price": "HK$／平方呎（按板面實碼計）|HK$ per sq. ft. (measured slab area)",
      "moq": "30 m²（可混色）|30 m² (mixed colours accepted)",
      "lead": "現貨 7–10 個工作天；訂造 20–30 天|Stock 7–10 working days; custom 20–30 days",
      "pack": "木箱 A 字架，每箱 8–10 片|Wooden A-frame crate, 8–10 slabs per crate",
    },
    "white-marble": {
      "grade": "A 級（無裂、無補膠）|Grade A (no cracks, no resin fill)",
      "slab": "3200×1600mm / 3050×1440mm",
      "thickness": "18 / 20 / 30mm（常備）；可訂 15–50mm|18 / 20 / 30 mm (stock); 15–50 mm to order",
      "tolerance": "±1.0mm（磨光面）|±1.0 mm (polished face)",
      "radio": "A 類 Class A（GB 6566）|Class A (GB 6566)",
      "edge": "直邊／圓邊／斜邊／羅馬邊|Straight / Bevel / Bullnose / Ogee",
      "install": "濕貼水泥砂漿／不鏽鋼乾掛|Wet-set mortar / Stainless steel dry-hang",
      "seam": "雲石膠無縫拼接（同紋對接）|Seamless epoxy jointing (pattern-matched)",
      "cert": "ISO 9001 · ASTM C97／C170 · GB 6566 A 類|ISO 9001 · ASTM C97/C170 · GB 6566 Class A",
      "maintain": "每 12 個月晶面保養一次|Crystallisation maintenance every 12 months",
      "warranty": "出廠品質保固 10 年（不含人為損壞）|10-year factory warranty (excl. accidental damage)",
      "price": "HK$／平方呎（按板面實碼計）|HK$ per sq. ft. (measured slab area)",
      "moq": "30 m²（可混色）|30 m² (mixed colours accepted)",
      "lead": "現貨 7–10 個工作天；訂造 20–30 天|Stock 7–10 working days; custom 20–30 days",
      "pack": "木箱 A 字架，每箱 8–10 片|Wooden A-frame crate, 8–10 slabs per crate",
    },
  };

  var PRODUCTS = {
    "beige-marble/century-beige": { cat: "beige-marble", slug: "century-beige", zh: "世紀米黃", en: "Century Beige", v: {
      "origin": "土耳其 Turkey|Turkey",
      "type": "天然雲石|Natural Marble",
      "colour": "米黃均勻底|Uniform beige",
      "density": "2.70",
      "absorption": "0.22",
      "compressive": "125",
      "flexural": "13.0",
      "mohs": "3.5",
      "abrasion": "≤ 21 mm|≤ 21 mm",
      "gloss": "84",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
    } },
    "beige-marble/emperador-gold": { cat: "beige-marble", slug: "emperador-gold", zh: "帝王金", en: "Emperador Gold", v: {
      "origin": "西班牙 Spain|Spain",
      "type": "天然雲石|Natural Marble",
      "colour": "深棕金網紋|Dark brown-gold veining",
      "density": "2.72",
      "absorption": "0.20",
      "compressive": "130",
      "flexural": "14.0",
      "mohs": "4.0",
      "abrasion": "≤ 20 mm|≤ 20 mm",
      "gloss": "85",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
    } },
    "beige-marble/rose-beige": { cat: "beige-marble", slug: "rose-beige", zh: "玫瑰米黃", en: "Rose Beige", v: {
      "origin": "土耳其 Turkey|Turkey",
      "type": "天然雲石|Natural Marble",
      "colour": "粉米黃|Rosy beige",
      "density": "2.68",
      "absorption": "0.25",
      "compressive": "116",
      "flexural": "12.0",
      "mohs": "3.0",
      "abrasion": "≤ 23 mm|≤ 23 mm",
      "gloss": "82",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
    } },
    "beige-marble/siena-yellow": { cat: "beige-marble", slug: "siena-yellow", zh: "西耶娜", en: "Siena Yellow", v: {
      "origin": "意大利 Italy|Italy",
      "type": "天然雲石|Natural Marble",
      "colour": "金黃褐紋|Golden-yellow with brown veins",
      "density": "2.69",
      "absorption": "0.24",
      "compressive": "119",
      "flexural": "12.5",
      "mohs": "3.0",
      "abrasion": "≤ 24 mm|≤ 24 mm",
      "gloss": "81",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
    } },
    "beige-marble/sunny-beige": { cat: "beige-marble", slug: "sunny-beige", zh: "莎安娜", en: "Sunny Beige", v: {
      "origin": "土耳其 Turkey|Turkey",
      "type": "天然雲石|Natural Marble",
      "colour": "淺米黃|Light beige",
      "density": "2.71",
      "absorption": "0.18",
      "compressive": "128",
      "flexural": "14.0",
      "mohs": "3.5",
      "abrasion": "≤ 20 mm|≤ 20 mm",
      "gloss": "86",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
    } },
    "beige-marble/white-magnolia": { cat: "beige-marble", slug: "white-magnolia", zh: "白玉蘭", en: "White Magnolia", v: {
      "origin": "土耳其 Turkey|Turkey",
      "type": "天然雲石|Natural Marble",
      "colour": "白米黃柔和紋|White-beige soft veining",
      "density": "2.70",
      "absorption": "0.19",
      "compressive": "122",
      "flexural": "13.0",
      "mohs": "3.5",
      "abrasion": "≤ 21 mm|≤ 21 mm",
      "gloss": "85",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
    } },
    "black-marble/black-galaxy": { cat: "black-marble", slug: "black-galaxy", zh: "黑金沙（花崗巖）", en: "Black Galaxy Granite", v: {
      "origin": "印度 India|India",
      "type": "天然花崗巖（麻石）|Natural Granite",
      "colour": "黑色金點|Black with gold flecks",
      "density": "2.75",
      "absorption": "0.11",
      "compressive": "222",
      "flexural": "20.5",
      "mohs": "6.5",
      "abrasion": "≤ 9 mm|≤ 9 mm",
      "gloss": "88",
      "acid": "耐酸性良好（適合廚房檯面）|Good acid resistance (suitable for kitchen tops)",
      "slab": "3050×1440mm（細金點料）|3050×1440 mm (fine gold fleck)",
    } },
    "black-marble/laurent-black-gold": { cat: "black-marble", slug: "laurent-black-gold", zh: "勞倫黑金", en: "Laurent Black Gold", v: {
      "origin": "意大利 Italy|Italy",
      "type": "天然雲石|Natural Marble",
      "colour": "黑色金白紋|Black with gold-white veining",
      "density": "2.71",
      "absorption": "0.15",
      "compressive": "145",
      "flexural": "16.0",
      "mohs": "3.5",
      "abrasion": "≤ 18 mm|≤ 18 mm",
      "gloss": "88",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
    } },
    "black-marble/nero-marquina": { cat: "black-marble", slug: "nero-marquina", zh: "黑白根", en: "Nero Marquina", v: {
      "origin": "西班牙 Spain|Spain",
      "type": "天然雲石|Natural Marble",
      "colour": "黑色白根紋|Black with white veining",
      "density": "2.70",
      "absorption": "0.17",
      "compressive": "136",
      "flexural": "15.0",
      "mohs": "3.5",
      "abrasion": "≤ 19 mm|≤ 19 mm",
      "gloss": "87",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
    } },
    "black-marble/nero-portoro": { cat: "black-marble", slug: "nero-portoro", zh: "黑金花", en: "Nero Portoro", v: {
      "origin": "意大利 Italy|Italy",
      "type": "天然雲石|Natural Marble",
      "colour": "黑色金紋|Black with golden veining",
      "density": "2.72",
      "absorption": "0.14",
      "compressive": "141",
      "flexural": "16.5",
      "mohs": "3.5",
      "abrasion": "≤ 17 mm|≤ 17 mm",
      "gloss": "89",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
    } },
    "black-marble/night-pearl": { cat: "black-marble", slug: "night-pearl", zh: "夜明珠", en: "Night Pearl", v: {
      "origin": "中國 China|China",
      "type": "天然雲石|Natural Marble",
      "colour": "黑色珠光|Black with pearlescent sheen",
      "density": "2.72",
      "absorption": "0.13",
      "compressive": "150",
      "flexural": "17.0",
      "mohs": "4.0",
      "abrasion": "≤ 17 mm|≤ 17 mm",
      "gloss": "88",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
    } },
    "black-marble/silver-white-dragon": { cat: "black-marble", slug: "silver-white-dragon", zh: "銀白龍", en: "Silver White Dragon", v: {
      "origin": "中國 China|China",
      "type": "天然雲石|Natural Marble",
      "colour": "黑白銀龍紋|Black-white silver dragon veining",
      "density": "2.73",
      "absorption": "0.12",
      "compressive": "155",
      "flexural": "18.0",
      "mohs": "4.0",
      "abrasion": "≤ 16 mm|≤ 16 mm",
      "gloss": "89",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
    } },
    "custom-craft/brass-inlay": { cat: "custom-craft", slug: "brass-inlay", zh: "嵌銅鑲嵌", en: "Brass Inlay", v: {
      "precision": "±0.3mm|±0.3 mm",
      "minfeature": "最小線寬 2.0mm|Minimum line width 2.0 mm",
      "thickness": "加工厚度 15–50mm|Machining thickness 15–50 mm",
    } },
    "custom-craft/curved-bending": { cat: "custom-craft", slug: "curved-bending", zh: "弧面熱彎", en: "Curved Bending", v: {
      "precision": "弧度高精 ±1.0mm|Arc accuracy ±1.0 mm",
      "minfeature": "最小彎曲半徑 R250mm|Minimum bend radius R250 mm",
      "thickness": "加工厚度 12–30mm|Machining thickness 12–30 mm",
    } },
    "custom-craft/edge-profiling": { cat: "custom-craft", slug: "edge-profiling", zh: "異型磨邊", en: "Edge Profiling", v: {
      "precision": "±0.5mm|±0.5 mm",
      "minfeature": "最小加工長度 150mm|Minimum length 150 mm",
      "thickness": "加工厚度 12–100mm|Machining thickness 12–100 mm",
    } },
    "custom-craft/relief-carving": { cat: "custom-craft", slug: "relief-carving", zh: "浮雕雕刻", en: "Relief Carving", v: {
      "precision": "浮雕深度公差 ±0.5mm|Relief depth ±0.5 mm",
      "minfeature": "最小線寬 3.0mm|Minimum line width 3.0 mm",
      "thickness": "加工厚度 20–200mm|Machining thickness 20–200 mm",
    } },
    "custom-craft/seamless-jointing": { cat: "custom-craft", slug: "seamless-jointing", zh: "無縫拼接", en: "Seamless Jointing", v: {
      "precision": "接縫 ≤ 0.5mm（目視無痕）|Joint ≤ 0.5 mm (visually invisible)",
      "minfeature": "單幅最長 6,000mm|Maximum single run 6,000 mm",
      "thickness": "加工厚度 15–30mm|Machining thickness 15–30 mm",
    } },
    "custom-craft/waterjet-inlay": { cat: "custom-craft", slug: "waterjet-inlay", zh: "水刀拼花", en: "Waterjet Inlay", v: {
      "precision": "±0.2mm|±0.2 mm",
      "minfeature": "最小拼花單元 8×8mm|Minimum inlay unit 8×8 mm",
      "thickness": "加工厚度 10–30mm|Machining thickness 10–30 mm",
    } },
    "engineered-stone/acrylic-solid-surface": { cat: "engineered-stone", slug: "acrylic-solid-surface", zh: "亞克力無縫人造石", en: "Acrylic Solid Surface", v: {
      "type": "亞克力實心面材|Acrylic Solid Surface",
      "origin": "中國（恆生自有配方）|China (Hengsheng proprietary formulation)",
      "colour": "純色／可調色（200+ 色）|Solid / custom colour (200+)",
      "slab": "3050×760mm / 3680×760mm",
      "thickness": "6 / 12.7mm",
      "density": "1.76",
      "absorption": "0.03",
      "compressive": "92",
      "flexural": "55",
      "mohs": "3.0",
      "abrasion": "≤ 45 mm³（Taber）|≤ 45 mm³ (Taber)",
      "gloss": "70",
      "heat": "≤ 80",
      "stain": "5 級（EN 438，無殘留）|Class 5 (EN 438, no residue)",
      "radio": "A 類 Class A（GB 6566）|Class A (GB 6566)",
      "seam": "專用膠無縫拼接（目視無痕）|Seamless jointing, visually invisible",
    } },
    "engineered-stone/composite-engineered-stone": { cat: "engineered-stone", slug: "composite-engineered-stone", zh: "複合人造崗石", en: "Composite Engineered Stone", v: {
      "type": "複合人造崗石|Composite Engineered Stone",
      "origin": "中國 China|China",
      "colour": "多色可訂|Multiple colours, customisable",
      "thickness": "15 / 18 / 20mm",
      "density": "2.45",
      "absorption": "0.05",
      "compressive": "122",
      "flexural": "26",
      "mohs": "5.0",
      "abrasion": "≤ 28 mm|≤ 28 mm",
      "gloss": "75",
      "heat": "≤ 130",
      "stain": "5 級|Class 5",
      "radio": "A 類 Class A（GB 6566）|Class A (GB 6566)",
    } },
    "engineered-stone/marble-look-stone": { cat: "engineered-stone", slug: "marble-look-stone", zh: "大理石紋人造石", en: "Marble-Look Engineered Stone", v: {
      "type": "大理石紋人造石|Marble-Look Engineered Stone",
      "origin": "中國 China|China",
      "colour": "仿雲石紋|Simulated marble veining",
      "thickness": "15 / 18 / 20mm",
      "density": "2.40",
      "absorption": "0.06",
      "compressive": "116",
      "flexural": "23",
      "mohs": "5.0",
      "abrasion": "≤ 30 mm|≤ 30 mm",
      "gloss": "80",
      "heat": "≤ 120",
      "stain": "5 級|Class 5",
      "radio": "A 類 Class A（GB 6566）|Class A (GB 6566)",
    } },
    "engineered-stone/quartz-stone": { cat: "engineered-stone", slug: "quartz-stone", zh: "石英石", en: "Quartz Stone", v: {
      "type": "石英石|Quartz Stone",
      "origin": "中國／西班牙|China / Spain",
      "colour": "純色／顆粒／仿紋|Solid / grain / veined",
      "thickness": "15 / 20 / 30mm",
      "density": "2.45",
      "absorption": "0.02",
      "compressive": "205",
      "flexural": "46",
      "mohs": "7.0",
      "abrasion": "≤ 15 mm|≤ 15 mm",
      "gloss": "85",
      "heat": "≤ 150",
      "stain": "5 級（EN 438）|Class 5 (EN 438)",
      "radio": "A 類 Class A（GB 6566）|Class A (GB 6566)",
    } },
    "engineered-stone/solid-colour-stone": { cat: "engineered-stone", slug: "solid-colour-stone", zh: "純色人造石", en: "Solid Colour Engineered Stone", v: {
      "type": "純色人造石|Solid Colour Engineered Stone",
      "origin": "中國 China|China",
      "colour": "純色系|Solid colour range",
      "thickness": "12 / 15 / 20mm",
      "density": "2.42",
      "absorption": "0.04",
      "compressive": "132",
      "flexural": "29",
      "mohs": "5.5",
      "abrasion": "≤ 26 mm|≤ 26 mm",
      "gloss": "78",
      "heat": "≤ 120",
      "stain": "5 級|Class 5",
      "radio": "A 類 Class A（GB 6566）|Class A (GB 6566)",
    } },
    "engineered-stone/terrazzo-stone": { cat: "engineered-stone", slug: "terrazzo-stone", zh: "水磨石人造石", en: "Terrazzo Engineered Stone", v: {
      "type": "水磨石人造石|Terrazzo Engineered Stone",
      "origin": "中國／意大利|China / Italy",
      "colour": "骨料碎花|Aggregate chip pattern",
      "slab": "3200×1600mm / 2400×1200mm",
      "thickness": "15 / 18 / 20mm",
      "density": "2.38",
      "absorption": "0.10",
      "compressive": "112",
      "flexural": "21",
      "mohs": "5.0",
      "abrasion": "≤ 32 mm|≤ 32 mm",
      "gloss": "70",
      "heat": "≤ 110",
      "stain": "4 級（建議封護）|Class 4 (sealing recommended)",
      "radio": "A 類 Class A（GB 6566）|Class A (GB 6566)",
    } },
    "engineered-stone/translucent-stone": { cat: "engineered-stone", slug: "translucent-stone", zh: "透光人造石", en: "Translucent Engineered Stone", v: {
      "type": "透光人造石|Translucent Engineered Stone",
      "origin": "中國 China|China",
      "colour": "半透乳白／彩色|Semi-translucent white / coloured",
      "thickness": "8 / 12 / 20mm",
      "density": "1.85",
      "absorption": "0.05",
      "compressive": "96",
      "flexural": "41",
      "mohs": "3.5",
      "abrasion": "≤ 40 mm³（Taber）|≤ 40 mm³ (Taber)",
      "gloss": "82",
      "heat": "≤ 80",
      "stain": "5 級|Class 5",
      "light": "35 – 55（背光可透）|35–55 (backlit)",
      "radio": "A 類 Class A（GB 6566）|Class A (GB 6566)",
    } },
    "engineering-stone-varieties/bollard-ball": { cat: "engineering-stone-varieties", slug: "bollard-ball", zh: "車檔石球", en: "Bollard Ball", v: {
      "size": "Ø300 / Ø400 / Ø500 / Ø600mm（實心整料）|Ø300 / Ø400 / Ø500 / Ø600 mm (solid)",
      "thickness": "實心球形，直徑即全高|Solid sphere; diameter = overall height",
      "load": "靜載 ≥ 5 噸|Static load ≥ 5 t",
      "standard": "BS EN 1342（花崗巖路緣／製品）|BS EN 1342 (granite setts & kerbs)",
      "price": "HK$／件|HK$ per piece",
      "moq": "10 件|10 pieces",
      "colour": "光面／荔枝面|Polished / Bush-hammered",
      "density": "2.72",
      "absorption": "0.28",
      "compressive": "198",
      "flexural": "15.5",
      "mohs": "6.5",
      "abrasion": "≤ 7.5 mm|≤ 7.5 mm",
    } },
    "engineering-stone-varieties/bollard-post": { cat: "engineering-stone-varieties", slug: "bollard-post", zh: "車檔柱", en: "Bollard Post", v: {
      "size": "150×150×600mm / 200×200×800mm / 250×250×1000mm",
      "thickness": "600 / 800 / 1000mm（柱高）|600 / 800 / 1000 mm (post height)",
      "load": "抗撞擊 ≥ 3 噸車輛低速衝擊|Impact resistant to 3 t vehicle at low speed",
      "standard": "BS EN 1342（花崗巖路緣／製品）|BS EN 1342 (granite setts & kerbs)",
      "price": "HK$／件|HK$ per piece",
      "moq": "10 件|10 pieces",
      "colour": "荔枝面／火燒面／光面|Bush-hammered / Flamed / Polished",
      "density": "2.70",
      "absorption": "0.32",
      "compressive": "186",
      "flexural": "14.5",
      "mohs": "6.5",
      "abrasion": "≤ 8.0 mm|≤ 8.0 mm",
    } },
    "engineering-stone-varieties/bushhammered-paving": { cat: "engineering-stone-varieties", slug: "bushhammered-paving", zh: "荔枝面地鋪石", en: "Bush-Hammered Paving", v: {
      "size": "300×300×50mm / 400×400×60mm / 600×600×60mm",
      "thickness": "50 / 60mm|50 / 60 mm",
      "load": "行人及輕型車輛（≤ 3.5 噸）|Pedestrian & light vehicles (≤ 3.5 t)",
      "standard": "BS EN 1341（天然石板地鋪）|BS EN 1341 (natural stone paving slabs)",
      "price": "HK$／m²|HK$ per m²",
      "moq": "30 m²",
      "colour": "荔枝面（防滑）|Bush-hammered (anti-slip)",
      "density": "2.68",
      "absorption": "0.35",
      "compressive": "178",
      "flexural": "13.5",
      "mohs": "6.0",
      "abrasion": "≤ 8.5 mm|≤ 8.5 mm",
      "slip": "R12（BS EN 14231）|R12 (BS EN 14231)",
    } },
    "engineering-stone-varieties/carved-stone-pier": { cat: "engineering-stone-varieties", slug: "carved-stone-pier", zh: "石墩（柱礎）", en: "Carved Stone Pier", v: {
      "size": "400×400×900mm / 500×500×1100mm",
      "thickness": "900 / 1100mm（墩高）|900 / 1100 mm (pier height)",
      "load": "軸心受壓 ≥ 200 kN|Axial load ≥ 200 kN",
      "standard": "BS EN 1342（花崗巖路緣／製品）|BS EN 1342 (granite setts & kerbs)",
      "price": "HK$／件|HK$ per piece",
      "moq": "10 件|10 pieces",
      "colour": "鑿面／光面／浮雕|Chiselled / Polished / Relief",
      "density": "2.74",
      "absorption": "0.26",
      "compressive": "205",
      "flexural": "16.5",
      "mohs": "6.5",
      "abrasion": "≤ 7.0 mm|≤ 7.0 mm",
    } },
    "engineering-stone-varieties/cobblestone": { cat: "engineering-stone-varieties", slug: "cobblestone", zh: "麻石小方石（卵石）", en: "Cobblestone", v: {
      "size": "100×100×50mm / 100×100×80mm / 200×100×80mm",
      "thickness": "50 / 80mm|50 / 80 mm",
      "load": "行人步道（≤ 1.5 噸）|Pedestrian walkway (≤ 1.5 t)",
      "standard": "BS EN 1341（天然石板地鋪）|BS EN 1341 (natural stone paving slabs)",
      "price": "HK$／m²|HK$ per m²",
      "moq": "30 m²",
      "colour": "自然劈面／機切面|Natural split / Sawn",
      "density": "2.65",
      "absorption": "0.42",
      "compressive": "162",
      "flexural": "12.0",
      "mohs": "6.0",
      "abrasion": "≤ 9.0 mm|≤ 9.0 mm",
      "slip": "R12（BS EN 14231）|R12 (BS EN 14231)",
    } },
    "engineering-stone-varieties/coping-stone": { cat: "engineering-stone-varieties", slug: "coping-stone", zh: "壓頂石（笠帽石）", en: "Coping Stone", v: {
      "size": "300×600×80mm / 400×600×100mm（含滴水槽）|300×600×80 mm / 400×600×100 mm (with drip groove)",
      "thickness": "80 / 100mm|80 / 100 mm",
      "load": "牆身壓頂，非承重|Wall coping, non-load-bearing",
      "standard": "BS EN 1342（花崗巖路緣／製品）|BS EN 1342 (granite setts & kerbs)",
      "price": "HK$／件|HK$ per piece",
      "moq": "20 件|20 pieces",
      "colour": "光面／荔枝面|Polished / Bush-hammered",
      "density": "2.71",
      "absorption": "0.30",
      "compressive": "192",
      "flexural": "15.0",
      "mohs": "6.5",
      "abrasion": "≤ 7.5 mm|≤ 7.5 mm",
    } },
    "engineering-stone-varieties/crazy-paving": { cat: "engineering-stone-varieties", slug: "crazy-paving", zh: "冰裂紋碎拼石", en: "Crazy Paving", v: {
      "size": "不規則 200–500mm，厚 30–50mm|Irregular 200–500 mm, 30–50 mm thick",
      "thickness": "30 – 50mm|30–50 mm",
      "load": "行人步道／庭園|Pedestrian / landscape",
      "standard": "BS EN 1341（天然石板地鋪）|BS EN 1341 (natural stone paving slabs)",
      "price": "HK$／m²|HK$ per m²",
      "moq": "30 m²",
      "colour": "自然面／荔枝面|Natural / Bush-hammered",
      "density": "2.66",
      "absorption": "0.40",
      "compressive": "168",
      "flexural": "12.5",
      "mohs": "6.0",
      "abrasion": "≤ 9.0 mm|≤ 9.0 mm",
      "slip": "R11（BS EN 14231）|R11 (BS EN 14231)",
    } },
    "engineering-stone-varieties/curb-stone": { cat: "engineering-stone-varieties", slug: "curb-stone", zh: "路緣石（石壆）", en: "Curb Stone", v: {
      "size": "1000×300×150mm / 1000×250×120mm",
      "thickness": "120 / 150mm|120 / 150 mm",
      "load": "可承受 30 噸重車側向|Withstands 30 t vehicle lateral load",
      "standard": "BS EN 1343（混凝土／石路緣石）|BS EN 1343 (kerbs)",
      "price": "HK$／件|HK$ per piece",
      "moq": "20 件|20 pieces",
      "colour": "機切面／荔枝面|Sawn / Bush-hammered",
      "density": "2.69",
      "absorption": "0.33",
      "compressive": "182",
      "flexural": "14.0",
      "mohs": "6.5",
      "abrasion": "≤ 8.0 mm|≤ 8.0 mm",
    } },
    "engineering-stone-varieties/curtain-wall-panel": { cat: "engineering-stone-varieties", slug: "curtain-wall-panel", zh: "外牆乾掛麻石板", en: "Curtain Wall Panel", v: {
      "size": "600×900×25mm / 800×1200×30mm",
      "thickness": "25 / 30mm|25 / 30 mm",
      "load": "抗風壓 ≥ 3.5 kPa（背栓錨固）|Wind load ≥ 3.5 kPa (undercut anchor)",
      "standard": "BS EN 1341 · 幕牆錨固拉拔測試|BS EN 1341 · Curtain-wall anchor pull-out test",
      "price": "HK$／m²|HK$ per m²",
      "moq": "50 m²",
      "colour": "光面／火燒面／荔枝面|Polished / Flamed / Bush-hammered",
      "density": "2.73",
      "absorption": "0.24",
      "compressive": "212",
      "flexural": "17.5",
      "mohs": "7.0",
      "abrasion": "≤ 6.5 mm|≤ 6.5 mm",
      "install": "不鏽鋼背栓式乾掛|Stainless steel undercut dry-hang",
    } },
    "engineering-stone-varieties/curved-curb": { cat: "engineering-stone-varieties", slug: "curved-curb", zh: "彎位路緣石（曲線道牙）", en: "Curved Curb", v: {
      "size": "弧長 500mm／件，半徑 R500–R3000mm|500 mm arc per piece, radius R500–R3000 mm",
      "thickness": "120 / 150mm|120 / 150 mm",
      "load": "可承受 30 噸重車側向|Withstands 30 t vehicle lateral load",
      "standard": "BS EN 1343（混凝土／石路緣石）|BS EN 1343 (kerbs)",
      "price": "HK$／件|HK$ per piece",
      "moq": "10 件|10 pieces",
      "colour": "機切面／荔枝面|Sawn / Bush-hammered",
      "density": "2.69",
      "absorption": "0.34",
      "compressive": "180",
      "flexural": "14.0",
      "mohs": "6.5",
      "abrasion": "≤ 8.0 mm|≤ 8.0 mm",
    } },
    "engineering-stone-varieties/engraved-name-stone": { cat: "engineering-stone-varieties", slug: "engraved-name-stone", zh: "門口石（刻字石）", en: "Engraved Name Stone", v: {
      "size": "1200×600×150mm / 1500×800×180mm",
      "thickness": "150 / 180mm|150 / 180 mm",
      "load": "景觀置石，非承重|Landscape feature stone, non-load-bearing",
      "standard": "BS EN 1342（花崗巖路緣／製品）|BS EN 1342 (granite setts & kerbs)",
      "price": "HK$／件|HK$ per piece",
      "moq": "1 件|1 piece",
      "colour": "光面＋陰刻填金|Polished with intaglio gold-filled lettering",
      "density": "2.72",
      "absorption": "0.27",
      "compressive": "196",
      "flexural": "15.5",
      "mohs": "6.5",
      "abrasion": "≤ 7.5 mm|≤ 7.5 mm",
    } },
    "engineering-stone-varieties/flamed-paving": { cat: "engineering-stone-varieties", slug: "flamed-paving", zh: "火燒面地鋪石", en: "Flamed Paving", v: {
      "size": "300×300×50mm / 600×600×60mm",
      "thickness": "50 / 60mm|50 / 60 mm",
      "load": "行人及車行道（≤ 10 噸）|Pedestrian & roadway (≤ 10 t)",
      "standard": "BS EN 1341（天然石板地鋪）|BS EN 1341 (natural stone paving slabs)",
      "price": "HK$／m²|HK$ per m²",
      "moq": "30 m²",
      "colour": "火燒面（防滑）|Flamed (anti-slip)",
      "density": "2.67",
      "absorption": "0.36",
      "compressive": "174",
      "flexural": "13.0",
      "mohs": "6.0",
      "abrasion": "≤ 8.5 mm|≤ 8.5 mm",
      "slip": "R11（BS EN 14231）|R11 (BS EN 14231)",
    } },
    "engineering-stone-varieties/mushroom-stone": { cat: "engineering-stone-varieties", slug: "mushroom-stone", zh: "蘑菇石（磊石）", en: "Mushroom Stone", v: {
      "size": "200×400×50–80mm（自然面）|200×400×50–80 mm (natural face)",
      "thickness": "50 – 80mm|50–80 mm",
      "load": "牆身飾面，非承重|Wall cladding, non-load-bearing",
      "standard": "BS EN 1342（花崗巖路緣／製品）|BS EN 1342 (granite setts & kerbs)",
      "price": "HK$／m²|HK$ per m²",
      "moq": "20 m²",
      "colour": "自然劈面蘑菇面|Natural split mushroom face",
      "density": "2.64",
      "absorption": "0.45",
      "compressive": "158",
      "flexural": "11.5",
      "mohs": "6.0",
      "abrasion": "≤ 9.5 mm|≤ 9.5 mm",
    } },
    "engineering-stone-varieties/step-tread": { cat: "engineering-stone-varieties", slug: "step-tread", zh: "石級（踏步石）", en: "Step Tread", v: {
      "size": "1200×350×50mm / 1500×350×60mm（含防滑槽）|1200×350×50 mm / 1500×350×60 mm (with anti-slip groove)",
      "thickness": "50 / 60mm|50 / 60 mm",
      "load": "集中荷載 ≥ 4 kN|Concentrated load ≥ 4 kN",
      "standard": "BS EN 1341（天然石板地鋪）|BS EN 1341 (natural stone paving slabs)",
      "price": "HK$／件|HK$ per piece",
      "moq": "10 件|10 pieces",
      "colour": "火燒面／荔枝面＋防滑槽|Flamed / Bush-hammered with anti-slip groove",
      "density": "2.70",
      "absorption": "0.31",
      "compressive": "188",
      "flexural": "14.5",
      "mohs": "6.5",
      "abrasion": "≤ 8.0 mm|≤ 8.0 mm",
      "slip": "R11（BS EN 14231）|R11 (BS EN 14231)",
    } },
    "engineering-stone-varieties/stone-balustrade": { cat: "engineering-stone-varieties", slug: "stone-balustrade", zh: "石欄河（麻石欄杆）", en: "Stone Balustrade", v: {
      "size": "立柱 150×150×1100mm；扶手 1200×120×80mm|Post 150×150×1100 mm; handrail 1200×120×80 mm",
      "thickness": "扶手 80mm／立柱 150mm|Handrail 80 mm / post 150 mm",
      "load": "水平推力 ≥ 1.5 kN/m|Horizontal thrust ≥ 1.5 kN/m",
      "standard": "BS EN 1342 · BS 6180（欄杆荷載）|BS EN 1342 · BS 6180 (barrier loads)",
      "price": "HK$／m（扶手計）|HK$ per m (handrail)",
      "moq": "10 m",
      "colour": "光面／荔枝面|Polished / Bush-hammered",
      "density": "2.73",
      "absorption": "0.25",
      "compressive": "208",
      "flexural": "17.0",
      "mohs": "7.0",
      "abrasion": "≤ 7.0 mm|≤ 7.0 mm",
    } },
    "engineering-stone-varieties/stone-drain-grate": { cat: "engineering-stone-varieties", slug: "stone-drain-grate", zh: "石水屜（去水石蓋）", en: "Stone Drain Grate", v: {
      "size": "400×600×60mm（開孔率 18%）|400×600×60 mm (18% open area)",
      "thickness": "60mm|60 mm",
      "load": "可承受 5 噸車輛碾壓|Withstands 5 t vehicle rolling load",
      "standard": "BS EN 1342（花崗巖路緣／製品）|BS EN 1342 (granite setts & kerbs)",
      "price": "HK$／件|HK$ per piece",
      "moq": "10 件|10 pieces",
      "colour": "機切面＋開孔|Sawn with slots",
      "density": "2.71",
      "absorption": "0.29",
      "compressive": "194",
      "flexural": "15.0",
      "mohs": "6.5",
      "abrasion": "≤ 7.5 mm|≤ 7.5 mm",
    } },
    "engineering-stone-varieties/tactile-paving": { cat: "engineering-stone-varieties", slug: "tactile-paving", zh: "導盲磚（盲人磚）", en: "Tactile Paving", v: {
      "size": "300×300×50mm（條狀／點狀）|300×300×50 mm (corduroy / blister)",
      "thickness": "50mm|50 mm",
      "load": "行人步道|Pedestrian walkway",
      "standard": "ISO 23599 · 香港運輸署《行人環境》指引|ISO 23599 · HK Transport Dept pedestrian guidance",
      "price": "HK$／件|HK$ per piece",
      "moq": "50 件|50 pieces",
      "colour": "機切面＋凸起導盲紋|Sawn with raised tactile profile",
      "density": "2.68",
      "absorption": "0.37",
      "compressive": "176",
      "flexural": "13.0",
      "mohs": "6.0",
      "abrasion": "≤ 8.5 mm|≤ 8.5 mm",
      "slip": "R12（BS EN 14231）|R12 (BS EN 14231)",
    } },
    "engineering-stone-varieties/tree-pit-stone": { cat: "engineering-stone-varieties", slug: "tree-pit-stone", zh: "樹池石（樹圈石）", en: "Tree Pit Stone", v: {
      "size": "1200×1200×100mm（4 件／套）|1200×1200×100 mm (4 pieces per set)",
      "thickness": "100mm|100 mm",
      "load": "樹池圍護，非承重|Tree pit surround, non-load-bearing",
      "standard": "BS EN 1342（花崗巖路緣／製品）|BS EN 1342 (granite setts & kerbs)",
      "price": "HK$／套|HK$ per set",
      "moq": "5 套|5 sets",
      "colour": "機切面／荔枝面|Sawn / Bush-hammered",
      "density": "2.66",
      "absorption": "0.41",
      "compressive": "165",
      "flexural": "12.0",
      "mohs": "6.0",
      "abrasion": "≤ 9.0 mm|≤ 9.0 mm",
    } },
    "granite-collection/black-galaxy": { cat: "granite-collection", slug: "black-galaxy", zh: "印度黑金沙", en: "Black Galaxy", v: {
      "origin": "印度 India|India",
      "type": "天然花崗巖（麻石）|Natural Granite",
      "colour": "黑色金沙點|Black with gold speckles",
      "density": "2.75",
      "absorption": "0.10",
      "compressive": "228",
      "flexural": "21.5",
      "mohs": "6.5",
      "abrasion": "≤ 8 mm|≤ 8 mm",
      "gloss": "90",
      "acid": "耐酸性良好（適合廚房檯面）|Good acid resistance (suitable for kitchen tops)",
    } },
    "granite-collection/blue-pearl": { cat: "granite-collection", slug: "blue-pearl", zh: "挪威藍珍珠", en: "Blue Pearl", v: {
      "origin": "挪威 Norway|Norway",
      "type": "天然花崗巖（麻石）|Natural Granite",
      "colour": "藍灰珍珠光|Blue-grey pearlescent",
      "density": "2.74",
      "absorption": "0.12",
      "compressive": "215",
      "flexural": "20.0",
      "mohs": "6.5",
      "abrasion": "≤ 9 mm|≤ 9 mm",
      "gloss": "88",
      "acid": "耐酸性良好（適合廚房檯面）|Good acid resistance (suitable for kitchen tops)",
    } },
    "granite-collection/brazil-gold": { cat: "granite-collection", slug: "brazil-gold", zh: "巴西金麻", en: "Brazilian Giallo", v: {
      "origin": "巴西 Brazil|Brazil",
      "type": "天然花崗巖（麻石）|Natural Granite",
      "colour": "金黃麻點|Golden speckled",
      "density": "2.68",
      "absorption": "0.18",
      "compressive": "190",
      "flexural": "17.0",
      "mohs": "6.0",
      "abrasion": "≤ 10 mm|≤ 10 mm",
      "gloss": "85",
      "acid": "耐酸性良好（適合廚房檯面）|Good acid resistance (suitable for kitchen tops)",
    } },
    "granite-collection/sesame-white": { cat: "granite-collection", slug: "sesame-white", zh: "芝麻白", en: "Sesame White", v: {
      "origin": "中國 China|China",
      "type": "天然花崗巖（麻石）|Natural Granite",
      "colour": "白底黑麻點|White with black speckles",
      "density": "2.66",
      "absorption": "0.25",
      "compressive": "176",
      "flexural": "15.0",
      "mohs": "6.0",
      "abrasion": "≤ 11 mm|≤ 11 mm",
      "gloss": "83",
      "acid": "耐酸性良好（適合廚房檯面）|Good acid resistance (suitable for kitchen tops)",
    } },
    "granite-collection/shanxi-black": { cat: "granite-collection", slug: "shanxi-black", zh: "山西黑", en: "Shanxi Black", v: {
      "origin": "中國 China|China",
      "type": "天然花崗巖（麻石）|Natural Granite",
      "colour": "純黑細粒|Jet black fine grain",
      "density": "2.78",
      "absorption": "0.08",
      "compressive": "242",
      "flexural": "22.0",
      "mohs": "7.0",
      "abrasion": "≤ 7 mm|≤ 7 mm",
      "gloss": "92",
      "acid": "耐酸性良好（適合廚房檯面）|Good acid resistance (suitable for kitchen tops)",
    } },
    "granite-collection/yellow-rust": { cat: "granite-collection", slug: "yellow-rust", zh: "黃鏽石", en: "Yellow Rust Stone", v: {
      "origin": "中國 China|China",
      "type": "天然花崗巖（麻石）|Natural Granite",
      "colour": "黃鏽斑駁|Yellow-rust mottled",
      "density": "2.64",
      "absorption": "0.30",
      "compressive": "166",
      "flexural": "14.0",
      "mohs": "6.0",
      "abrasion": "≤ 12 mm|≤ 12 mm",
      "gloss": "82",
      "acid": "耐酸性良好（適合廚房檯面）|Good acid resistance (suitable for kitchen tops)",
    } },
    "grey-marble/italian-grey": { cat: "grey-marble", slug: "italian-grey", zh: "意大利灰", en: "Italian Grey", v: {
      "origin": "意大利 Italy|Italy",
      "type": "天然雲石|Natural Marble",
      "colour": "中灰細紋|Mid-grey fine veining",
      "density": "2.71",
      "absorption": "0.16",
      "compressive": "132",
      "flexural": "15.0",
      "mohs": "3.5",
      "abrasion": "≤ 19 mm|≤ 19 mm",
      "gloss": "86",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
    } },
    "grey-marble/light-grey-net": { cat: "grey-marble", slug: "light-grey-net", zh: "淺灰網", en: "Light Grey Net", v: {
      "origin": "中國 China|China",
      "type": "天然雲石|Natural Marble",
      "colour": "淺灰網紋|Light grey net veining",
      "density": "2.70",
      "absorption": "0.18",
      "compressive": "128",
      "flexural": "14.0",
      "mohs": "3.5",
      "abrasion": "≤ 20 mm|≤ 20 mm",
      "gloss": "85",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
    } },
    "grey-marble/moonlight-grey": { cat: "grey-marble", slug: "moonlight-grey", zh: "月光灰", en: "Moonlight Grey", v: {
      "origin": "土耳其 Turkey|Turkey",
      "type": "天然雲石|Natural Marble",
      "colour": "月光灰|Moonlight grey",
      "density": "2.69",
      "absorption": "0.20",
      "compressive": "120",
      "flexural": "13.0",
      "mohs": "3.0",
      "abrasion": "≤ 22 mm|≤ 22 mm",
      "gloss": "83",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
    } },
    "grey-marble/paolo-dark-grey": { cat: "grey-marble", slug: "paolo-dark-grey", zh: "保羅深灰", en: "Paolo Dark Grey", v: {
      "origin": "意大利 Italy|Italy",
      "type": "天然雲石|Natural Marble",
      "colour": "深灰直紋|Dark grey linear veining",
      "density": "2.72",
      "absorption": "0.15",
      "compressive": "138",
      "flexural": "16.0",
      "mohs": "3.5",
      "abrasion": "≤ 18 mm|≤ 18 mm",
      "gloss": "87",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
    } },
    "grey-marble/volakas-grey": { cat: "grey-marble", slug: "volakas-grey", zh: "希臘雅士白", en: "Greek Volakas", v: {
      "origin": "希臘 Greece|Greece",
      "type": "天然雲石|Natural Marble",
      "colour": "灰白雲霧紋|Grey-white cloudy veining",
      "density": "2.72",
      "absorption": "0.16",
      "compressive": "133",
      "flexural": "15.0",
      "mohs": "3.5",
      "abrasion": "≤ 20 mm|≤ 20 mm",
      "gloss": "85",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
      "slab": "3050×1440mm（灰調料）|3050×1440 mm (grey tone)",
    } },
    "grey-marble/yundola-grey": { cat: "grey-marble", slug: "yundola-grey", zh: "雲多拉灰", en: "Yundola Grey", v: {
      "origin": "中國 China|China",
      "type": "天然雲石|Natural Marble",
      "colour": "雲多拉灰|Yundola grey",
      "density": "2.70",
      "absorption": "0.19",
      "compressive": "126",
      "flexural": "14.0",
      "mohs": "3.5",
      "abrasion": "≤ 20 mm|≤ 20 mm",
      "gloss": "85",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
    } },
    "luxury-stone/amazon-green": { cat: "luxury-stone", slug: "amazon-green", zh: "亞馬遜綠", en: "Amazon Green", v: {
      "origin": "巴西 Brazil|Brazil",
      "type": "天然石英岩|Natural Quartzite",
      "colour": "翠綠帶白紋|Emerald green with white veining",
      "density": "2.68",
      "absorption": "0.15",
      "compressive": "192",
      "flexural": "18.0",
      "mohs": "6.5",
      "abrasion": "≤ 10 mm|≤ 10 mm",
      "gloss": "88",
      "acid": "耐酸性良好（適合廚房檯面）|Good acid resistance (suitable for kitchen tops)",
    } },
    "luxury-stone/amethyst-gem": { cat: "luxury-stone", slug: "amethyst-gem", zh: "紫水晶", en: "Amethyst", v: {
      "origin": "巴西／烏拉圭|Brazil / Uruguay",
      "type": "半寶石石材|Semi-precious Stone",
      "colour": "紫色晶體|Purple crystal",
      "density": "2.65",
      "absorption": "0.20",
      "compressive": "150",
      "flexural": "14.0",
      "mohs": "7.0",
      "abrasion": "≤ 12 mm|≤ 12 mm",
      "gloss": "90",
      "acid": "耐酸性良好（適合廚房檯面）|Good acid resistance (suitable for kitchen tops)",
    } },
    "luxury-stone/blue-jade": { cat: "luxury-stone", slug: "blue-jade", zh: "藍翡翠", en: "Blue Jade", v: {
      "origin": "中國／緬甸|China / Myanmar",
      "type": "天然玉石|Natural Jade Stone",
      "colour": "藍綠玉質|Blue-green jade",
      "density": "2.70",
      "absorption": "0.12",
      "compressive": "182",
      "flexural": "17.0",
      "mohs": "6.0",
      "abrasion": "≤ 11 mm|≤ 11 mm",
      "gloss": "89",
      "acid": "耐酸性良好（適合廚房檯面）|Good acid resistance (suitable for kitchen tops)",
    } },
    "luxury-stone/malachite-gem": { cat: "luxury-stone", slug: "malachite-gem", zh: "孔雀石", en: "Malachite", v: {
      "origin": "剛果（金）|DR Congo",
      "type": "半寶石石材|Semi-precious Stone",
      "colour": "孔雀綠環紋|Malachite green banding",
      "density": "2.75",
      "absorption": "0.18",
      "compressive": "140",
      "flexural": "13.0",
      "mohs": "4.0",
      "abrasion": "≤ 14 mm|≤ 14 mm",
      "gloss": "86",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
    } },
    "luxury-stone/pandora-quartzite": { cat: "luxury-stone", slug: "pandora-quartzite", zh: "潘朵拉", en: "Pandora Quartzite", v: {
      "origin": "巴西 Brazil|Brazil",
      "type": "天然石英岩|Natural Quartzite",
      "colour": "灰白流紋|Grey-white flowing veins",
      "density": "2.66",
      "absorption": "0.22",
      "compressive": "186",
      "flexural": "18.0",
      "mohs": "6.5",
      "abrasion": "≤ 10 mm|≤ 10 mm",
      "gloss": "87",
      "acid": "耐酸性良好（適合廚房檯面）|Good acid resistance (suitable for kitchen tops)",
    } },
    "luxury-stone/red-dragon-jade": { cat: "luxury-stone", slug: "red-dragon-jade", zh: "紅龍玉", en: "Red Dragon Jade", v: {
      "origin": "中國 China|China",
      "type": "天然玉石|Natural Jade Stone",
      "colour": "紅金龍紋|Red-gold dragon veining",
      "density": "2.72",
      "absorption": "0.10",
      "compressive": "200",
      "flexural": "19.0",
      "mohs": "6.5",
      "abrasion": "≤ 9 mm|≤ 9 mm",
      "gloss": "90",
      "acid": "耐酸性良好（適合廚房檯面）|Good acid resistance (suitable for kitchen tops)",
    } },
    "marble-furniture/bench-stool": { cat: "marble-furniture", slug: "bench-stool", zh: "長凳・坐凳", en: "Marble Bench & Stool", v: {
      "size": "1200×400×450mm / 1500×450×450mm",
      "thickness": "檯面 40 / 50mm|Top 40 / 50 mm",
      "load": "靜載 ≥ 250 kg|Static load ≥ 250 kg",
      "colour": "選材：卡拉拉白・爵士白・黑白根・意大利灰|Stone: Bianco Carrara / Statuario / Nero Marquina / Italian Grey",
      "density": "2.70",
      "absorption": "0.18",
      "compressive": "128",
      "flexural": "14.0",
      "mohs": "3.5",
      "abrasion": "≤ 22 mm|≤ 22 mm",
      "gloss": "88",
    } },
    "marble-furniture/coffee-table": { cat: "marble-furniture", slug: "coffee-table", zh: "雲石茶几", en: "Marble Coffee Table", v: {
      "size": "1100×600×420mm / 1300×700×420mm",
      "thickness": "檯面 20 / 30mm|Top 20 / 30 mm",
      "load": "均佈 ≥ 80 kg|Distributed ≥ 80 kg",
      "colour": "選材：魚肚白・大花白・雲多拉灰|Stone: Calacatta Gold / Arabescato / Yundola Grey",
      "density": "2.71",
      "absorption": "0.16",
      "compressive": "132",
      "flexural": "15.0",
      "mohs": "3.5",
      "abrasion": "≤ 21 mm|≤ 21 mm",
      "gloss": "89",
    } },
    "marble-furniture/console-table": { cat: "marble-furniture", slug: "console-table", zh: "玄關幾・條案", en: "Marble Console Table", v: {
      "size": "1200×350×800mm / 1400×400×800mm",
      "thickness": "檯面 20mm|Top 20 mm",
      "load": "均佈 ≥ 60 kg|Distributed ≥ 60 kg",
      "colour": "選材：白玉蘭・莎安娜・淺灰網|Stone: White Magnolia / Sunny Beige / Light Grey Net",
      "density": "2.69",
      "absorption": "0.20",
      "compressive": "120",
      "flexural": "13.0",
      "mohs": "3.5",
      "abrasion": "≤ 23 mm|≤ 23 mm",
      "gloss": "86",
    } },
    "marble-furniture/counter-bar": { cat: "marble-furniture", slug: "counter-bar", zh: "接待臺・吧檯", en: "Marble Reception & Bar Counter", v: {
      "size": "2400×600×1100mm / 3000×700×1100mm",
      "thickness": "檯面 30 / 50mm|Top 30 / 50 mm",
      "load": "≥ 150 kg／m|≥ 150 kg per metre",
      "colour": "選材：黑金花・勞倫黑金・石英石（耐污首選）|Stone: Nero Portoro / Laurent Black Gold / Quartz (best stain resistance)",
      "density": "2.72",
      "absorption": "0.15",
      "compressive": "140",
      "flexural": "16.0",
      "mohs": "4.0",
      "abrasion": "≤ 19 mm|≤ 19 mm",
      "gloss": "90",
    } },
    "marble-furniture/dining-table": { cat: "marble-furniture", slug: "dining-table", zh: "雲石餐桌", en: "Marble Dining Table", v: {
      "size": "1600×900×750mm / 1800×900×750mm / 2000×1000×750mm / 2400×1100×750mm",
      "thickness": "檯面 20 / 30mm|Top 20 / 30 mm",
      "load": "均佈 ≥ 120 kg|Distributed ≥ 120 kg",
      "colour": "選材：卡拉拉白・爵士白・金碧輝煌・黑白根|Stone: Bianco Carrara / Statuario / Emperador Gold / Nero Marquina",
      "density": "2.70",
      "absorption": "0.19",
      "compressive": "125",
      "flexural": "14.0",
      "mohs": "3.5",
      "abrasion": "≤ 22 mm|≤ 22 mm",
      "gloss": "88",
    } },
    "marble-furniture/side-table": { cat: "marble-furniture", slug: "side-table", zh: "邊幾・角幾", en: "Marble Side Table", v: {
      "size": "Ø450×550mm / 500×500×550mm|Ø450×550 mm / 500×500×550 mm",
      "thickness": "檯面 20mm|Top 20 mm",
      "load": "均佈 ≥ 40 kg|Distributed ≥ 40 kg",
      "colour": "選材：玫瑰米黃・西耶娜・月光灰|Stone: Rose Beige / Siena Yellow / Moonlight Grey",
      "density": "2.68",
      "absorption": "0.22",
      "compressive": "116",
      "flexural": "12.0",
      "mohs": "3.0",
      "abrasion": "≤ 24 mm|≤ 24 mm",
      "gloss": "85",
    } },
    "marble-furniture/vanity-basin": { cat: "marble-furniture", slug: "vanity-basin", zh: "浴室櫃・洗手盆", en: "Marble Vanity & Basin", v: {
      "size": "800×500×850mm / 1000×520×850mm / 1200×550×850mm",
      "thickness": "檯面 20 / 30mm|Top 20 / 30 mm",
      "load": "≥ 60 kg（含滿水盆）|≥ 60 kg (incl. filled basin)",
      "colour": "選材：石英石・人造石（防水防污首選）／雲石|Stone: Quartz / Engineered stone (best waterproof) / Marble",
      "density": "2.71",
      "absorption": "0.14",
      "compressive": "138",
      "flexural": "16.0",
      "mohs": "4.0",
      "abrasion": "≤ 20 mm|≤ 20 mm",
      "gloss": "89",
    } },
    "new-arrivals/amazon-green": { cat: "new-arrivals", slug: "amazon-green", zh: "亞馬遜綠", en: "Amazon Green Quartzite", v: {
      "origin": "巴西 Brazil|Brazil",
      "type": "天然石英岩|Natural Quartzite",
      "colour": "翠綠帶白紋|Emerald green with white veining",
      "density": "2.69",
      "absorption": "0.14",
      "compressive": "196",
      "flexural": "18.5",
      "mohs": "6.5",
      "abrasion": "≤ 9 mm|≤ 9 mm",
      "gloss": "89",
      "acid": "耐酸性良好（適合廚房檯面）|Good acid resistance (suitable for kitchen tops)",
      "slab": "3200×1600mm（限量現貨大板）|3200×1600 mm (limited jumbo stock)",
      "grade": "特選級（對紋拼花優先配對）|Selected grade (book-match priority)",
      "lead": "現貨 5–7 個工作天|Stock 5–7 working days",
      "moq": "20 m²（新品推廣）|20 m² (launch promotion)",
      "price": "HK$／平方呎（新品推廣價）|HK$ per sq. ft. (launch price)",
    } },
    "new-arrivals/blue-onyx": { cat: "new-arrivals", slug: "blue-onyx", zh: "藍翡翠", en: "Blue Onyx", v: {
      "origin": "伊朗／巴基斯坦|Iran / Pakistan",
      "type": "天然玉石（半寶石）|Natural Onyx (semi-precious)",
      "colour": "藍色透光紋|Blue translucent veining",
      "density": "2.68",
      "absorption": "0.16",
      "compressive": "165",
      "flexural": "14.5",
      "mohs": "3.5",
      "abrasion": "≤ 14 mm|≤ 14 mm",
      "gloss": "90",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
      "light": "25 – 40（背光可透）|25–40 (backlit)",
      "lead": "現貨 5–7 個工作天|Stock 5–7 working days",
      "moq": "15 m²（新品推廣）|15 m² (launch promotion)",
    } },
    "new-arrivals/calacatta-gold": { cat: "new-arrivals", slug: "calacatta-gold", zh: "魚肚金", en: "Calacatta Gold Marble", v: {
      "origin": "意大利 Italy|Italy",
      "type": "天然雲石|Natural Marble",
      "colour": "白色底金紋|White with gold veining",
      "density": "2.71",
      "absorption": "0.15",
      "compressive": "138",
      "flexural": "16.0",
      "mohs": "3.5",
      "abrasion": "≤ 19 mm|≤ 19 mm",
      "gloss": "89",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
      "slab": "3200×1600mm（限量現貨大板）|3200×1600 mm (limited jumbo stock)",
      "lead": "現貨 5–7 個工作天|Stock 5–7 working days",
      "moq": "20 m²（新品推廣）|20 m² (launch promotion)",
    } },
    "new-arrivals/glacier-white-quartzite": { cat: "new-arrivals", slug: "glacier-white-quartzite", zh: "冰川白", en: "Glacier White Quartzite", v: {
      "origin": "巴西 Brazil|Brazil",
      "type": "天然石英岩|Natural Quartzite",
      "colour": "冰川白流紋|Glacier white flowing veins",
      "density": "2.70",
      "absorption": "0.14",
      "compressive": "205",
      "flexural": "19.5",
      "mohs": "7.0",
      "abrasion": "≤ 9 mm|≤ 9 mm",
      "gloss": "90",
      "acid": "耐酸性良好（適合廚房檯面）|Good acid resistance (suitable for kitchen tops)",
    } },
    "new-arrivals/panda-white": { cat: "new-arrivals", slug: "panda-white", zh: "熊貓白", en: "Panda White Marble", v: {
      "origin": "中國 China|China",
      "type": "天然雲石|Natural Marble",
      "colour": "黑白對比紋|Black-white contrast veining",
      "density": "2.72",
      "absorption": "0.13",
      "compressive": "148",
      "flexural": "17.0",
      "mohs": "4.0",
      "abrasion": "≤ 17 mm|≤ 17 mm",
      "gloss": "89",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
    } },
    "new-arrivals/shangri-la-gold": { cat: "new-arrivals", slug: "shangri-la-gold", zh: "香格里拉金", en: "Shangri-la Gold", v: {
      "origin": "土耳其 Turkey|Turkey",
      "type": "天然雲石|Natural Marble",
      "colour": "金黃流紋|Golden flowing veins",
      "density": "2.71",
      "absorption": "0.17",
      "compressive": "134",
      "flexural": "15.0",
      "mohs": "3.5",
      "abrasion": "≤ 19 mm|≤ 19 mm",
      "gloss": "87",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
    } },
    "project-stone/langhua-white": { cat: "project-stone", slug: "langhua-white", zh: "浪花白", en: "Langhua White Granite", v: {
      "origin": "中國福建|Fujian, China",
      "type": "天然花崗巖（麻石）|Natural Granite",
      "colour": "白底浪花紋|White with wave patterns",
      "density": "2.68",
      "absorption": "0.22",
      "compressive": "185",
      "flexural": "16.0",
      "mohs": "6.5",
      "abrasion": "≤ 10 mm|≤ 10 mm",
      "gloss": "86",
      "acid": "耐酸性良好（適合廚房檯面）|Good acid resistance (suitable for kitchen tops)",
    } },
    "project-stone/mongolian-black": { cat: "project-stone", slug: "mongolian-black", zh: "蒙古黑", en: "Mongolian Black Granite", v: {
      "origin": "中國內蒙古|Inner Mongolia, China",
      "type": "天然花崗巖（麻石）|Natural Granite",
      "colour": "純黑細粒|Jet black fine grain",
      "density": "2.80",
      "absorption": "0.09",
      "compressive": "245",
      "flexural": "22.5",
      "mohs": "7.0",
      "abrasion": "≤ 7 mm|≤ 7 mm",
      "gloss": "92",
      "acid": "耐酸性良好（適合廚房檯面）|Good acid resistance (suitable for kitchen tops)",
    } },
    "project-stone/pearl-flower": { cat: "project-stone", slug: "pearl-flower", zh: "珍珠花", en: "Pearl Flower Granite", v: {
      "origin": "中國山東|Shandong, China",
      "type": "天然花崗巖（麻石）|Natural Granite",
      "colour": "灰白珍珠點|Grey-white pearl speckles",
      "density": "2.67",
      "absorption": "0.24",
      "compressive": "178",
      "flexural": "15.5",
      "mohs": "6.5",
      "abrasion": "≤ 11 mm|≤ 11 mm",
      "gloss": "85",
      "acid": "耐酸性良好（適合廚房檯面）|Good acid resistance (suitable for kitchen tops)",
    } },
    "project-stone/qing-bluestone": { cat: "project-stone", slug: "qing-bluestone", zh: "青石（石灰岩）", en: "Qing Bluestone (Limestone)", v: {
      "origin": "中國四川|Sichuan, China",
      "type": "天然石灰岩|Natural Limestone",
      "colour": "青灰細密|Blue-grey dense",
      "density": "2.62",
      "absorption": "1.80",
      "compressive": "105",
      "flexural": "12.0",
      "mohs": "4.5",
      "abrasion": "≤ 16 mm|≤ 16 mm",
      "gloss": "70",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
    } },
    "project-stone/sesame-grey": { cat: "project-stone", slug: "sesame-grey", zh: "芝麻灰", en: "Sesame Grey Granite", v: {
      "origin": "中國福建|Fujian, China",
      "type": "天然花崗巖（麻石）|Natural Granite",
      "colour": "淺灰黑麻點|Light grey with black speckles",
      "density": "2.66",
      "absorption": "0.26",
      "compressive": "172",
      "flexural": "15.0",
      "mohs": "6.5",
      "abrasion": "≤ 11 mm|≤ 11 mm",
      "gloss": "84",
      "acid": "耐酸性良好（適合廚房檯面）|Good acid resistance (suitable for kitchen tops)",
    } },
    "project-stone/wulianhua": { cat: "project-stone", slug: "wulianhua", zh: "五蓮花", en: "Wulianhua Granite", v: {
      "origin": "中國山東|Shandong, China",
      "type": "天然花崗巖（麻石）|Natural Granite",
      "colour": "灰白五蓮花紋|Grey-white Wulianhua pattern",
      "density": "2.65",
      "absorption": "0.28",
      "compressive": "168",
      "flexural": "14.5",
      "mohs": "6.0",
      "abrasion": "≤ 12 mm|≤ 12 mm",
      "gloss": "83",
      "acid": "耐酸性良好（適合廚房檯面）|Good acid resistance (suitable for kitchen tops)",
    } },
    "travertine-sandstone/australian-sandstone": { cat: "travertine-sandstone", slug: "australian-sandstone", zh: "澳洲砂岩", en: "Australian Sandstone", v: {
      "origin": "澳洲 Australia|Australia",
      "type": "天然砂岩|Natural Sandstone",
      "colour": "淺米黃砂粒|Light beige sandy grain",
      "density": "2.35",
      "absorption": "3.50",
      "compressive": "76",
      "flexural": "8.0",
      "mohs": "6.0",
      "abrasion": "≤ 20 mm|≤ 20 mm",
      "gloss": "55",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
      "freeze": "25 次凍融循環合格|25 freeze-thaw cycles pass",
    } },
    "travertine-sandstone/classic-beige-travertine": { cat: "travertine-sandstone", slug: "classic-beige-travertine", zh: "米黃洞石", en: "Classic Beige Travertine", v: {
      "origin": "土耳其 Turkey|Turkey",
      "type": "天然洞石|Natural Travertine",
      "colour": "米黃孔洞|Beige with pores",
      "density": "2.40",
      "absorption": "2.80",
      "compressive": "82",
      "flexural": "9.0",
      "mohs": "4.0",
      "abrasion": "≤ 18 mm|≤ 18 mm",
      "gloss": "60",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
      "freeze": "25 次凍融循環合格|25 freeze-thaw cycles pass",
    } },
    "travertine-sandstone/portuguese-white-sandstone": { cat: "travertine-sandstone", slug: "portuguese-white-sandstone", zh: "葡萄牙白砂岩", en: "Portuguese White Sandstone", v: {
      "origin": "葡萄牙 Portugal|Portugal",
      "type": "天然砂岩|Natural Sandstone",
      "colour": "白砂細粒|White fine grain",
      "density": "2.38",
      "absorption": "3.20",
      "compressive": "71",
      "flexural": "7.5",
      "mohs": "6.0",
      "abrasion": "≤ 21 mm|≤ 21 mm",
      "gloss": "56",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
      "freeze": "25 次凍融循環合格|25 freeze-thaw cycles pass",
    } },
    "travertine-sandstone/red-travertine": { cat: "travertine-sandstone", slug: "red-travertine", zh: "紅洞石", en: "Red Travertine", v: {
      "origin": "伊朗 Iran|Iran",
      "type": "天然洞石|Natural Travertine",
      "colour": "紅褐紋理|Red-brown veining",
      "density": "2.42",
      "absorption": "2.60",
      "compressive": "86",
      "flexural": "10.0",
      "mohs": "4.0",
      "abrasion": "≤ 17 mm|≤ 17 mm",
      "gloss": "62",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
      "freeze": "25 次凍融循環合格|25 freeze-thaw cycles pass",
    } },
    "travertine-sandstone/roman-travertine": { cat: "travertine-sandstone", slug: "roman-travertine", zh: "羅馬洞石", en: "Roman Travertine", v: {
      "origin": "意大利 Italy|Italy",
      "type": "天然洞石|Natural Travertine",
      "colour": "米白經典洞|Classic ivory pores",
      "density": "2.44",
      "absorption": "2.40",
      "compressive": "91",
      "flexural": "11.0",
      "mohs": "4.0",
      "abrasion": "≤ 16 mm|≤ 16 mm",
      "gloss": "64",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
      "freeze": "25 次凍融循環合格|25 freeze-thaw cycles pass",
    } },
    "travertine-sandstone/silver-travertine": { cat: "travertine-sandstone", slug: "silver-travertine", zh: "銀灰洞石", en: "Silver Travertine", v: {
      "origin": "土耳其 Turkey|Turkey",
      "type": "天然洞石|Natural Travertine",
      "colour": "銀灰孔洞|Silver-grey pores",
      "density": "2.41",
      "absorption": "2.70",
      "compressive": "84",
      "flexural": "9.5",
      "mohs": "4.0",
      "abrasion": "≤ 18 mm|≤ 18 mm",
      "gloss": "61",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
      "freeze": "25 次凍融循環合格|25 freeze-thaw cycles pass",
    } },
    "white-marble/arabescato-white": { cat: "white-marble", slug: "arabescato-white", zh: "大花白", en: "Arabescato White", v: {
      "origin": "意大利 Italy|Italy",
      "type": "天然雲石|Natural Marble",
      "colour": "白色底灰網紋|White with grey veining",
      "density": "2.70",
      "absorption": "0.18",
      "compressive": "128",
      "flexural": "14.5",
      "mohs": "3.5",
      "abrasion": "≤ 22 mm（BS EN 14157）|≤ 22 mm (BS EN 14157)",
      "gloss": "85",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
    } },
    "white-marble/calacatta-gold": { cat: "white-marble", slug: "calacatta-gold", zh: "魚肚白（卡拉卡塔金）", en: "Calacatta Gold", v: {
      "origin": "意大利 Italy|Italy",
      "type": "天然雲石|Natural Marble",
      "colour": "白色底金灰紋|White with gold-grey veining",
      "density": "2.71",
      "absorption": "0.16",
      "compressive": "135",
      "flexural": "15.5",
      "mohs": "3.5",
      "abrasion": "≤ 20 mm|≤ 20 mm",
      "gloss": "88",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
    } },
    "white-marble/carrara-white": { cat: "white-marble", slug: "carrara-white", zh: "卡拉拉白", en: "Bianco Carrara", v: {
      "origin": "意大利 Italy|Italy",
      "type": "天然雲石|Natural Marble",
      "colour": "灰白細網紋|Grey-white fine veining",
      "density": "2.69",
      "absorption": "0.20",
      "compressive": "112",
      "flexural": "12.0",
      "mohs": "3.0",
      "abrasion": "≤ 25 mm|≤ 25 mm",
      "gloss": "82",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
    } },
    "white-marble/greek-volakas": { cat: "white-marble", slug: "greek-volakas", zh: "希臘雅士白", en: "Greek Volakas", v: {
      "origin": "希臘 Greece|Greece",
      "type": "天然雲石|Natural Marble",
      "colour": "純白底淡灰紋|Pure white with light grey veining",
      "density": "2.72",
      "absorption": "0.15",
      "compressive": "138",
      "flexural": "16.0",
      "mohs": "3.5",
      "abrasion": "≤ 19 mm|≤ 19 mm",
      "gloss": "86",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
    } },
    "white-marble/statuario-white": { cat: "white-marble", slug: "statuario-white", zh: "爵士白", en: "Statuario White", v: {
      "origin": "意大利 Italy|Italy",
      "type": "天然雲石|Natural Marble",
      "colour": "高白底深灰紋|High white with bold grey veining",
      "density": "2.71",
      "absorption": "0.14",
      "compressive": "142",
      "flexural": "17.0",
      "mohs": "3.5",
      "abrasion": "≤ 18 mm|≤ 18 mm",
      "gloss": "90",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
    } },
    "white-marble/thassos-snow-white": { cat: "white-marble", slug: "thassos-snow-white", zh: "雪花白", en: "Thassos Snow White", v: {
      "origin": "希臘 Greece|Greece",
      "type": "天然雲石|Natural Marble",
      "colour": "雪白結晶|Snow-white crystalline",
      "density": "2.83",
      "absorption": "0.10",
      "compressive": "152",
      "flexural": "18.5",
      "mohs": "3.5",
      "abrasion": "≤ 16 mm|≤ 16 mm",
      "gloss": "92",
      "acid": "不耐酸（碳酸鈣材質，忌醋／檸檬／強酸清潔劑）|Acid-sensitive (calcium carbonate; avoid vinegar, lemon & strong acid cleaners)",
    } },
  };

  var MISSING = '不支援／無|Not applicable';

  // ---- 解析「中文|英文」----
  function pick(v, lang) {
    if (v == null || v === '') return null;
    var s = String(v);
    var i = s.indexOf('|');
    if (i < 0) return s;
    return (lang === 'en') ? s.slice(i + 1) : s.slice(0, i);
  }

  // ---- 取得某產品的完整參數（品類預設 + 逐款覆蓋）----
  function getSpec(id) {
    var p = PRODUCTS[id];
    if (!p) return null;
    var d = CAT_DEFAULTS[p.cat] || {};
    var out = { cat: p.cat, slug: p.slug, zh: p.zh, en: p.en, values: {} };
    FIELDS.forEach(function (f) {
      var v = (p.v && f.key in p.v) ? p.v[f.key] : (f.key in d ? d[f.key] : null);
      if (v != null && v !== '') out.values[f.key] = v;
    });
    return out;
  }

  // ---- 取得單一欄位顯示值（含缺失標記）----
  function getField(id, key, lang) {
    var s = getSpec(id);
    if (!s) return null;
    var raw = s.values[key];
    if (raw == null) return pick(MISSING, lang);
    return pick(raw, lang);
  }

  window.HSST_SPECS = {
    version: '2026.09.23',
    GROUPS: GROUPS,
    FIELDS: FIELDS,
    CAT_DEFAULTS: CAT_DEFAULTS,
    PRODUCTS: PRODUCTS,
    CAT_ZH: "{\"white-marble\": \"白雲石\", \"beige-marble\": \"米黃雲石\", \"black-marble\": \"黑雲石\", \"grey-marble\": \"灰雲石\", \"granite-collection\": \"花崗巖（麻石）\", \"luxury-stone\": \"奢石\", \"travertine-sandstone\": \"洞石・砂岩\", \"engineered-stone\": \"人造石\", \"engineering-stone-varieties\": \"工程石製品\", \"marble-furniture\": \"雲石家俬\", \"project-stone\": \"工程專供石材\", \"new-arrivals\": \"新品上架\", \"custom-craft\": \"訂造工藝\"}",
    CAT_EN: "{\"white-marble\": \"White Marble\", \"beige-marble\": \"Beige Marble\", \"black-marble\": \"Black Marble\", \"grey-marble\": \"Grey Marble\", \"granite-collection\": \"Granite Collection\", \"luxury-stone\": \"Luxury Stone\", \"travertine-sandstone\": \"Travertine & Sandstone\", \"engineered-stone\": \"Engineered Stone\", \"engineering-stone-varieties\": \"Engineering Stone Products\", \"marble-furniture\": \"Marble Furniture\", \"project-stone\": \"Project Stone\", \"new-arrivals\": \"New Arrivals\", \"custom-craft\": \"Custom Craft\"}",
    MISSING: MISSING,
    pick: pick,
    getSpec: getSpec,
    getField: getField,
    lang: function () {
      var l = (document.documentElement.lang || '').toLowerCase();
      return l.indexOf('en') === 0 ? 'en' : 'zh';
    }
  };
})();
